version: "3.8"

services:
  pgsql:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: mario
      POSTGRES_DB: todos
    volumes:
      - todos-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  python:
    build: .
    depends_on:
      - pgsql
    ports:
      - "5007:5007"
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: "true"
      FLASK_ENV: development

volumes:
  todos-vol:
