"""Add owner column for todos model

Revision ID: 5b5e73d61132
Revises: 5cc3cd9d6afc
Create Date: 2024-03-27 11:19:51.801137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5e73d61132'
down_revision = '5cc3cd9d6afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
